# Generated by Django 3.0.3 on 2020-03-03 09:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import twin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_projet', models.CharField(max_length=30, verbose_name='Titre du projet')),
                ('duree_du_projet', models.IntegerField(default=0, verbose_name='Duree estimee')),
                ('temps_alloue_par_le_createur', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Temps alloue')),
                ('besoins', models.TextField(max_length=250)),
                ('description', models.TextField(max_length=250)),
                ('est_valide', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30, verbose_name='Prenom')),
                ('prenom', models.CharField(max_length=30, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, validators=[twin.models.is_esprit_mail], verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='twin.User')),
            ],
            bases=('twin.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='twin.User')),
            ],
            bases=('twin.user',),
        ),
        migrations.CreateModel(
            name='MembershipInProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_allocated_by_member', models.IntegerField(verbose_name='Temps alloué par le membre')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twin.Project')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twin.Student')),
            ],
            options={
                'unique_together': {('projet', 'etudiant')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='createur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_owner', to='twin.Student'),
        ),
        migrations.AddField(
            model_name='project',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='les_membres', through='twin.MembershipInProject', to='twin.Student'),
        ),
        migrations.AddField(
            model_name='project',
            name='superviseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_coach', to='twin.Coach'),
        ),
    ]
